#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "src/main/resources/web"
HOSTS = (
    "index.html", "cvss-v31.html", "cisa-kev.html", "epss.html",
    "asset-context.html", "network-reachability.html", "business-impact.html",
    "assets.html", "asset-links.html",
)

host = (WEB / "index.html").read_text(encoding="utf-8")
for name in HOSTS:
    text = (WEB / name).read_text(encoding="utf-8")
    if text != host:
        raise AssertionError(
            f"{name}: activation UI must preserve byte-identical Frontend V2 hosts"
        )
    if re.search(r"[\u0600-\u06ff]", text):
        raise AssertionError(f"{name}: operator UI must remain English-only")

contract = "RISK_METHOD_SELECTION_POLICY_ACTIVATION_UI_V1"
if host.count(contract) != 1:
    raise AssertionError("Activation UI contract marker must occur exactly once")
start = host.index(contract)
end = host.index("</script>", start)
ui = host[start:end]

doc = (ROOT / "docs/RISK_METHOD_SELECTION_POLICY_ACTIVATION_UI_V1.md").read_text(
    encoding="utf-8"
)
policy_verifier = (ROOT / "scripts/verify-risk-method-selection-policy-ui.py").read_text(
    encoding="utf-8"
)
verify_sh = (ROOT / "scripts/verify.sh").read_text(encoding="utf-8")

required = (
    "CURRENT_IS_GREATEST_EXPLICIT_ACTIVATION_REVISION_NEVER_POLICY_REVISION",
    "Active risk policy",
    "Current means the greatest explicit activation revision only",
    "Policy revision order and catalog order never select the active method",
    "/api/v1/risk-method-selection-policy-activation/current",
    "Never activated is different from explicitly CLEARED",
    "Activation is an auditable control-plane decision",
    "highest policy revision",
    "recordedAt is never generated by the browser",
    "Select explicit activation state…",
    "activationRevision.value=''",
    "state.value=''",
    "recordedAt.value=''",
    "policyRevision.value=''",
    "policySha.value=''",
    "/api/v1/risk-method-selection-policy-activation-events/${revision}/ACTIVE/${policyRev}/${sha}/${encodeURIComponent(when)}",
    "/api/v1/risk-method-selection-policy-activation-events/${revision}/CLEARED/${encodeURIComponent(when)}",
    "{method:'POST'}",
    "Operator role is required to append activation events",
    "the UI will not auto-increment it",
    "The exact policy revision and SHA requested for ACTIVE do not exist",
    "/api/v1/risk-method-selection-policy-activations/${revision}/${sha}",
    "No fallback event is selected",
    "readRevision.value=''",
    "readSha.value=''",
    "response?.headers.get('ETag')",
    "response?.headers.get('Location')",
    "changedBy",
    "eventSha256",
    "canonicalPayloadFormat",
)
for needle in required:
    if needle not in ui:
        raise AssertionError(f"Activation UI missing invariant {needle!r}")

# recordedAt must be a deliberate UTC instant and never browser-generated.
if "const exactInstant=value=>/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,9})?Z$/" not in ui:
    raise AssertionError("Activation UI must require an explicit UTC Z recordedAt instant")

for forbidden in (
    "localStorage",
    "sessionStorage",
    "document.cookie",
    "innerHTML",
    "document.write",
    "Date.now(",
    "new Date()",
    "toISOString()",
    "Math.max",
    "maxRevision",
    "activationRevision+1",
    "activationRevision + 1",
    "policyRevision+1",
    "policyRevision + 1",
    "latest=true",
    "defaultPolicy",
    "preferredPolicy",
    "priorityTier",
    "priorityScore",
    "slaDays",
    "treatmentDecision",
    "remediationDeadline",
):
    if forbidden in ui:
        raise AssertionError(
            f"Activation UI contains forbidden implicit construct {forbidden!r}"
        )

# There must be no activation collection/list read; current and exact identity are the only reads.
if re.search(
    r"api\(\s*['\"]\/api\/v1\/risk-method-selection-policy-activations['\"]",
    ui,
):
    raise AssertionError("Activation UI must not list activation events")
if "/api/v1/risk-method-selection-policy-activations?" in ui:
    raise AssertionError("Activation UI must not query an activation collection")

# All activation-write identity fields must explicitly start empty before the append handler.
activation_input = ui.index("'aria-label':'Explicit activation revision'")
state_input = ui.index("'aria-label':'Explicit activation state'", activation_input)
recorded_input = ui.index("'aria-label':'Explicit activation recordedAt'", state_input)
policy_revision_input = ui.index("'aria-label':'Exact active policy revision'", recorded_input)
policy_sha_input = ui.index("'aria-label':'Exact active policy SHA-256'", policy_revision_input)
activation_empty = ui.index("activationRevision.value=''", policy_sha_input)
state_empty = ui.index("state.value=''", activation_empty)
recorded_empty = ui.index("recordedAt.value=''", state_empty)
policy_revision_empty = ui.index("policyRevision.value=''", recorded_empty)
policy_sha_empty = ui.index("policySha.value=''", policy_revision_empty)
append_handler = ui.index("Append explicit activation event", policy_sha_empty)
if not (
    activation_input < state_input < recorded_input < policy_revision_input < policy_sha_input
    < activation_empty < state_empty < recorded_empty < policy_revision_empty
    < policy_sha_empty < append_handler
):
    raise AssertionError("Activation append controls must start from explicit empty identities")

# Exact historical read must also begin empty and require both immutable identifiers.
read_revision = ui.index("'aria-label':'Exact activation revision to read'", append_handler)
read_sha = ui.index("'aria-label':'Exact activation event SHA-256 to read'", read_revision)
read_revision_empty = ui.index("readRevision.value=''", read_sha)
read_sha_empty = ui.index("readSha.value=''", read_revision_empty)
read_handler = ui.index("Read exact activation event", read_sha_empty)
if not read_revision < read_sha < read_revision_empty < read_sha_empty < read_handler:
    raise AssertionError("Exact activation read must start with empty revision and event SHA")

# Policy Admin V1 and Activation UI V1 must remain separate script contracts.
for marker in (
    'script_start = host.rfind("<script>", 0, start)',
    'script_end = host.index("</script>", start)',
    'ui = host[script_start:script_end]',
):
    if marker not in policy_verifier:
        raise AssertionError("Policy Admin V1 verifier must isolate its own inline script")
for marker in (
    "RISK_METHOD_SELECTION_POLICY_ADMIN_UI_V1",
    "DERIVED_RISK_METHODOLOGY_COMPARISON_UI_V1",
    "RBVM_FORMULA_V1_PRESENTATION_UI_V1",
    "FINDING_CONTEXT_ASSOCIATION_UI_V1",
):
    if marker not in host:
        raise AssertionError(f"Shared host lost existing UI contract {marker}")

normalized_doc = " ".join(doc.split())
for marker in (
    "`never activated` is different from `CLEARED`.",
    "greatest explicit **activation revision**",
    "The browser never computes `max + 1`",
    "never substitutes browser time for `recordedAt`",
    "Historical activation reads require both immutable identifiers",
    "Installing a V25 policy revision does not activate it.",
    "not stored in `localStorage`, `sessionStorage`, cookies, or query-state defaults",
    "no Priority, Treatment, SLA, remediation deadline",
):
    if marker not in normalized_doc:
        raise AssertionError(f"Activation UI documentation missing {marker!r}")

if 'verify-risk-method-selection-policy-activation-ui.py' not in verify_sh:
    raise AssertionError("Activation UI verifier is not wired into scripts/verify.sh")

print("Risk Method Selection Policy Activation UI checks: PASS")
