#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$ROOT_DIR/scripts/compile.sh" --tests

MAIN_CLASSES="$ROOT_DIR/build/manual/main"
TEST_CLASSES="$ROOT_DIR/build/manual/test"

java -ea -cp "$MAIN_CLASSES:$TEST_CLASSES" io.rbvm.csv.PlatformSelfTest
python3 "$ROOT_DIR/scripts/verify-api.py"
python3 "$ROOT_DIR/scripts/verify-sql.py"
python3 "$ROOT_DIR/scripts/verify-managed-asset-registry.py"
python3 "$ROOT_DIR/scripts/verify-scanner-managed-asset-link.py"
python3 "$ROOT_DIR/scripts/verify-scanner-managed-asset-link-api.py"
python3 "$ROOT_DIR/scripts/verify-managed-asset-api.py"
python3 "$ROOT_DIR/scripts/verify-decision-methodology-sql.py"
python3 "$ROOT_DIR/scripts/verify-decision-input-snapshot-sql.py"
python3 "$ROOT_DIR/scripts/verify-decision-input-builder.py"
python3 "$ROOT_DIR/scripts/verify-decision-input-resolver.py"
python3 "$ROOT_DIR/scripts/verify-decision-input-runtime.py"
python3 "$ROOT_DIR/scripts/verify-decision-input-http.py"
python3 "$ROOT_DIR/scripts/verify-decision-input-v2.py"
python3 "$ROOT_DIR/scripts/verify-decision-input-v3.py"
python3 "$ROOT_DIR/scripts/verify-formula-readiness.py"
python3 "$ROOT_DIR/scripts/verify-formula-readiness-final.py"
python3 "$ROOT_DIR/scripts/verify-formula-golden-cases.py"
python3 "$ROOT_DIR/scripts/verify-formula-v1.py"
python3 "$ROOT_DIR/scripts/verify-formula-v1-runtime.py"
python3 "$ROOT_DIR/scripts/verify-formula-v1-explanation.py"
python3 "$ROOT_DIR/scripts/verify-derived-risk-methodologies.py"
python3 "$ROOT_DIR/scripts/verify-derived-risk-result-canonicalization.py"
python3 "$ROOT_DIR/scripts/verify-derived-risk-result-persistence.py"
python3 "$ROOT_DIR/scripts/verify-derived-risk-materialization.py"
python3 "$ROOT_DIR/scripts/verify-derived-risk-result-api.py"
python3 "$ROOT_DIR/scripts/verify-derived-risk-result-http.py"
python3 "$ROOT_DIR/scripts/verify-derived-risk-ui.py"
python3 "$ROOT_DIR/scripts/verify-risk-method-selection-policy.py"
python3 "$ROOT_DIR/scripts/verify-risk-method-selection-policy-api.py"
python3 "$ROOT_DIR/scripts/verify-risk-method-selection-policy-ui.py"
python3 "$ROOT_DIR/scripts/verify-risk-method-selection-policy-activation.py"
python3 "$ROOT_DIR/scripts/verify-active-risk-method-execution-binding.py"
python3 "$ROOT_DIR/scripts/verify-active-risk-method-execution-api.py"
python3 "$ROOT_DIR/scripts/verify-risk-method-selection-policy-activation-api.py"
python3 "$ROOT_DIR/scripts/verify-risk-method-selection-policy-activation-ui.py"
python3 "$ROOT_DIR/scripts/verify-active-risk-method-execution-ui.py"
python3 "$ROOT_DIR/scripts/verify-resolved-active-risk-method.py"
python3 "$ROOT_DIR/scripts/verify-formula-catalog.py"
python3 "$ROOT_DIR/scripts/verify-formula-ui.py"
python3 "$ROOT_DIR/scripts/verify-formula-result-persistence.py"
python3 "$ROOT_DIR/scripts/verify-formula-result-api.py"
python3 "$ROOT_DIR/scripts/verify-formula-result-http.py"
python3 "$ROOT_DIR/scripts/verify-formula-result-materialization.py"
python3 "$ROOT_DIR/scripts/verify-formula-result-materialization-http.py"
python3 "$ROOT_DIR/scripts/verify-finding-context-association.py"
python3 "$ROOT_DIR/scripts/verify-finding-context-association-sql.py"
python3 "$ROOT_DIR/scripts/verify-finding-context-association-registries.py"
python3 "$ROOT_DIR/scripts/verify-finding-context-association-api.py"
python3 "$ROOT_DIR/scripts/verify-finding-context-association-ui.py"
python3 "$ROOT_DIR/scripts/verify-web.py"
python3 "$ROOT_DIR/scripts/verify-frontend-system.py"
python3 "$ROOT_DIR/scripts/verify-local-launch-auth.py"
python3 "$ROOT_DIR/scripts/verify-managed-assets-ui.py" "$ROOT_DIR/src/main/resources/web/assets.html"
python3 "$ROOT_DIR/scripts/verify-asset-links-ui.py"
python3 "$ROOT_DIR/scripts/verify-workflows.py"
python3 "$ROOT_DIR/scripts/verify-enrichment.py"
python3 "$ROOT_DIR/scripts/verify-public-vulnerability-intel.py"
python3 "$ROOT_DIR/scripts/verify-cvss-v4-official.py"
python3 "$ROOT_DIR/scripts/verify-cvss-v4-enrichment.py"
python3 "$ROOT_DIR/scripts/verify-cvss-v4-semantic-resolution.py"
python3 "$ROOT_DIR/scripts/verify-csv-first-enrichment.py"
python3 "$ROOT_DIR/scripts/verify-csv-first-http.py"
python3 "$ROOT_DIR/scripts/verify-customer-asset-flow.py"
python3 "$ROOT_DIR/scripts/verify-customer-bundle-v3.py"
python3 "$ROOT_DIR/scripts/verify-csv-run-review.py"
python3 "$ROOT_DIR/scripts/verify-csv-run-evidence-analysis.py"
python3 "$ROOT_DIR/scripts/verify-nvd-cvss-v31.py"
python3 "$ROOT_DIR/scripts/verify-cvss-v31-handoff.py"
python3 "$ROOT_DIR/scripts/verify-cisa-kev-source.py"
python3 "$ROOT_DIR/scripts/verify-cisa-kev-contract.py"
python3 "$ROOT_DIR/scripts/verify-cisa-kev-handoff.py"
python3 "$ROOT_DIR/scripts/verify-cisa-kev-refresh.py"
python3 "$ROOT_DIR/scripts/verify-first-epss-source.py"
python3 "$ROOT_DIR/scripts/verify-epss-contract.py"
python3 "$ROOT_DIR/scripts/verify-epss-handoff.py"
python3 "$ROOT_DIR/scripts/verify-epss-refresh.py"
python3 "$ROOT_DIR/scripts/verify-canonical-intelligence-refresh.py"
python3 "$ROOT_DIR/scripts/verify-intelligence-refresh-deployment.py"
python3 "$ROOT_DIR/scripts/verify-dedicated-intelligence-read.py"
for script in "$ROOT_DIR"/scripts/*.sh; do
  bash -n "$script"
done
printf '%s\n' 'Shell script structural checks: PASS'

if [[ $# -gt 0 ]]; then
  java -cp "$MAIN_CLASSES" io.rbvm.csv.CsvContractCli "$1"
fi
